// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVzaWVuXuIrdfBjCLD-1h7sAtzmiYZgNg',
    appId: '1:696348254357:web:b0e8d7e7f38204b9e0fb9c',
    messagingSenderId: '696348254357',
    projectId: 'codingmindproject',
    authDomain: 'codingmindproject.firebaseapp.com',
    storageBucket: 'codingmindproject.firebasestorage.app',
    measurementId: 'G-P22YFR8D1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARIRb5EzfxvEbiojNJxuK2eWxW1R_YmQ0',
    appId: '1:696348254357:android:590803b0774b1e3ee0fb9c',
    messagingSenderId: '696348254357',
    projectId: 'codingmindproject',
    storageBucket: 'codingmindproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxsXyF30avoPdt2qOgJCO86OdwdsuZjgg',
    appId: '1:696348254357:ios:863c23f9be9ed0fce0fb9c',
    messagingSenderId: '696348254357',
    projectId: 'codingmindproject',
    storageBucket: 'codingmindproject.firebasestorage.app',
    iosBundleId: 'com.example.codingmindProject',
  );
}
